List<Map<String, dynamic>> cities = [
  {
    "id": 1,
    "nameInArabic": "القاهرة",
    "nameInEnglish": "Cairo",
    "citiesAndVillages": [
      {"id": 1, "nameInArabic": "الأميرية، القاهرة", "nameInEnglish": "Amiriyyah"},
      {"id": 2, "nameInArabic": "البساتين، القاهرة", "nameInEnglish": "Basateen"},
      {"id": 3, "nameInArabic": "التبين، القاهرة", "nameInEnglish": "Tebeen"},
      {"id": 4, "nameInArabic": "التجمع الثالث، القاهرة", "nameInEnglish": "The 3rd District"},
      {"id": 5, "nameInArabic": "الجمالية، القاهرة", "nameInEnglish": "Gamaleya"},
      {"id": 6, "nameInArabic": "الحلمية، القاهرة", "nameInEnglish": "Helmeya"},
      {"id": 7, "nameInArabic": "الحلمية الجديدة، القاهرة", "nameInEnglish": "Alhelmeya Algadeda"},
      {"id": 8, "nameInArabic": "الخليفة، القاهرة", "nameInEnglish": "Khalifa"},
      {"id": 9, "nameInArabic": "الدراسة، القاهرة", "nameInEnglish": "Darrasa"},
      {"id": 10, "nameInArabic": "الدرب الأحمر، القاهرة", "nameInEnglish": "Darb Al-ahmar"},
      {"id": 11, "nameInArabic": "الزاوية الحمراء، القاهرة", "nameInEnglish": "Alzawya Al-hamra"},
      {"id": 12, "nameInArabic": "الزمالك، القاهرة", "nameInEnglish": "Zamalek"},
      {"id": 13, "nameInArabic": "الزيتون، القاهرة", "nameInEnglish": "Zaytoun"},
      {"id": 14, "nameInArabic": "الساحل، القاهرة", "nameInEnglish": "Al-sahel"},
      {"id": 15, "nameInArabic": "السيدة زينب، القاهرة", "nameInEnglish": "Al-sayeda Zeinab"},
      {"id": 16, "nameInArabic": "الشرابية، القاهرة", "nameInEnglish": "Al-sharabeya"},
      {"id": 17, "nameInArabic": "العاشر من رمضان، القاهرة", "nameInEnglish": "10th Ramadan City"},
      {"id": 18, "nameInArabic": "العاصمة الإدارية الجديدة، القاهرة", "nameInEnglish": "New Capital City"},
      {"id": 19, "nameInArabic": "العباسية، القاهرة", "nameInEnglish": "Abasiya"},
      {"id": 20, "nameInArabic": "العبور، القاهرة", "nameInEnglish": "Obour City"},
      {"id": 21, "nameInArabic": "العتبة، القاهرة", "nameInEnglish": "Ataba"},
      {"id": 22, "nameInArabic": "القاهرة الجديدة - التجمع الأول، القاهرة", "nameInEnglish": "First Settlement"},
      {"id": 23, "nameInArabic": "القاهرة الجديدة - الأندلس، القاهرة", "nameInEnglish": "New Cairo Andalous"},
      {"id": 24, "nameInArabic": "القاهرة الجديدة - التجمع الخامس، القاهرة", "nameInEnglish": "Fifth Settlement"},
      {"id": 25, "nameInArabic": "القاهرة الجديدة - لوتس، القاهرة", "nameInEnglish": "New Cairo Lotus"},
      {"id": 26, "nameInArabic": "القاهرة الجديدة - مدينة الرحاب، القاهرة", "nameInEnglish": "Rehab City"},
      {"id": 27, "nameInArabic": "القطامية، القاهرة", "nameInEnglish": "Katameya"},
      {"id": 28, "nameInArabic": "الماظة، القاهرة", "nameInEnglish": "Almazah"},
      {"id": 29, "nameInArabic": "المرج، القاهرة", "nameInEnglish": "Al-marj"},
      {"id": 30, "nameInArabic": "المطرية، القاهرة", "nameInEnglish": "Matareya"},
      {"id": 31, "nameInArabic": "المعادي، القاهرة", "nameInEnglish": "Maadi"},
      {"id": 32, "nameInArabic": "المعصره، القاهرة", "nameInEnglish": "Ma-sara"},
      {"id": 33, "nameInArabic": "المقطم، القاهرة", "nameInEnglish": "Al-Mokattam"},
      {"id": 34, "nameInArabic": "المنيرة الجديدة، القاهرة", "nameInEnglish": "Al-mounira Al-gadeda"},
      {"id": 35, "nameInArabic": "المنيل، القاهرة", "nameInEnglish": "Al-manial"},
      {"id": 36, "nameInArabic": "الموسكي، القاهرة", "nameInEnglish": "Moski"},
      {"id": 37, "nameInArabic": "النزهة، القاهرة", "nameInEnglish": "Nozha Cairo"},
      {"id": 38, "nameInArabic": "الوايلي، القاهرة", "nameInEnglish": "Waili"},
      {"id": 39, "nameInArabic": "باب الشعرية، القاهرة", "nameInEnglish": "Bab Al-shereia"},
      {"id": 40, "nameInArabic": "بولاق، القاهرة", "nameInEnglish": "Boulaq"},
      {"id": 41, "nameInArabic": "بيت الوطن، القاهرة", "nameInEnglish": "Bait El-watan"},
      {"id": 42, "nameInArabic": "جاردن سيتي، القاهرة", "nameInEnglish": "Garden City"},
      {"id": 43, "nameInArabic": "حدائق القبة، القاهرة", "nameInEnglish": "Hadayek Al-kobba"},
      {"id": 44, "nameInArabic": "حدائق حلوان، القاهرة", "nameInEnglish": "Hadayek Helwan"},
      {"id": 45, "nameInArabic": "حلوان، القاهرة", "nameInEnglish": "Helwan"},
      {"id": 46, "nameInArabic": "دار السلام، القاهرة", "nameInEnglish": "Dar Al-salaam"},
      {"id": 47, "nameInArabic": "رمسيس و امتداد رمسيس، القاهرة", "nameInEnglish": "Ramses Ramses Extension"},
      {"id": 48, "nameInArabic": "روض الفرج، القاهرة", "nameInEnglish": "Rod Al-farag"},
      {"id": 49, "nameInArabic": "زهراء المعادى، القاهرة", "nameInEnglish": "Zahraa Al-maadi"},
      {"id": 50, "nameInArabic": "شبرا، القاهرة", "nameInEnglish": "Shubra"},
      {"id": 51, "nameInArabic": "شيراتون، القاهرة", "nameInEnglish": "Sheraton"},
      {"id": 52, "nameInArabic": "طرة، القاهرة", "nameInEnglish": "Tura"},
      {"id": 53, "nameInArabic": "عزبة النخل، القاهرة", "nameInEnglish": "Izbat An-nakhl"},
      {"id": 54, "nameInArabic": "عين شمس، القاهرة", "nameInEnglish": "Ain Shams"},
      {"id": 55, "nameInArabic": "قصر النيل، القاهرة", "nameInEnglish": "Qasr Al-nil"},
      {"id": 56, "nameInArabic": "مدينة 15 مايو، القاهرة", "nameInEnglish": "15 May City"},
      {"id": 57, "nameInArabic": "مدينة السلام، القاهرة", "nameInEnglish": "Salam City"},
      {"id": 58, "nameInArabic": "مدينة الشروق، القاهرة", "nameInEnglish": "Shorouk City"},
      {"id": 59, "nameInArabic": "مدينة المستقبل، القاهرة", "nameInEnglish": "Future City"},
      {"id": 60, "nameInArabic": "مدينة بدر، القاهرة", "nameInEnglish": "Badr-City"},
      {"id": 61, "nameInArabic": "مدينة نصر، القاهرة", "nameInEnglish": "Nasr City"},
      {"id": 62, "nameInArabic": "مدينتي، القاهرة", "nameInEnglish": "Madinaty"},
      {"id": 63, "nameInArabic": "مسطرد، القاهرة", "nameInEnglish": "Musturad"},
      {"id": 64, "nameInArabic": "مصر الجديدة، القاهرة", "nameInEnglish": "Heliopolis"},
      {"id": 65, "nameInArabic": "مصر القديمة، القاهرة", "nameInEnglish": "Masr Al-kadema"},
      {"id": 66, "nameInArabic": "هليوبوليس الجديدة، القاهرة", "nameInEnglish": "New Heliopolis"},
      {"id": 67, "nameInArabic": "وسط القاهرة، القاهرة", "nameInEnglish": "Downtown Cairo"}
    ]
  },
  {
    "id": 2,
    "nameInArabic": "أسوان",
    "nameInEnglish": "Aswan",
    "citiesAndVillages": [
      {"id": 68, "nameInArabic": "ابو الريش، أسوان", "nameInEnglish": "Abou Al-reish"},
      {"id": 69, "nameInArabic": "ابو سمبل، أسوان", "nameInEnglish": "Abou Simbel"},
      {"id": 70, "nameInArabic": "ادفو، أسوان", "nameInEnglish": "Edfu"},
      {"id": 71, "nameInArabic": "البصيلية، أسوان", "nameInEnglish": "Basiliah"},
      {"id": 72, "nameInArabic": "الرديسية، أسوان", "nameInEnglish": "Rdesiah"},
      {"id": 73, "nameInArabic": "السباعية، أسوان", "nameInEnglish": "Sebaeiah"},
      {"id": 74, "nameInArabic": "دراو، أسوان", "nameInEnglish": "Daraw"},
      {"id": 75, "nameInArabic": "صحارى، أسوان", "nameInEnglish": "Sahara"},
      {"id": 76, "nameInArabic": "كلابشة، أسوان", "nameInEnglish": "Kalabsha"},
      {"id": 77, "nameInArabic": "كوم امبو، أسوان", "nameInEnglish": "Kom Ombo"},
      {"id": 78, "nameInArabic": "نصر النوبة، أسوان", "nameInEnglish": "Nasr Al-noba"}
    ]
  },
  {
    "id": 3,
    "nameInArabic": "أسيوط",
    "nameInEnglish": "Asyut",
    "citiesAndVillages": [
      {"id": 79, "nameInArabic": "أبنوب، أسيوط", "nameInEnglish": "Abnub"},
      {"id": 80, "nameInArabic": "أبو تيج، أسيوط", "nameInEnglish": "Abu Teeg"},
      {"id": 81, "nameInArabic": "أسيوط الجديدة، أسيوط", "nameInEnglish": "New Assiut"},
      {"id": 82, "nameInArabic": "البدارى، أسيوط", "nameInEnglish": "Badari"},
      {"id": 83, "nameInArabic": "الفتح، أسيوط", "nameInEnglish": "Fateh"},
      {"id": 84, "nameInArabic": "القوصيه، أسيوط", "nameInEnglish": "Qusiya"},
      {"id": 85, "nameInArabic": "ديروط، أسيوط", "nameInEnglish": "Dairut"},
      {"id": 86, "nameInArabic": "ساحل سليم، أسيوط", "nameInEnglish": "Sahel-selim"},
      {"id": 87, "nameInArabic": "صدفا، أسيوط", "nameInEnglish": "Sedfa"},
      {"id": 88, "nameInArabic": "منفلوط، أسيوط", "nameInEnglish": "Manfalut"}
    ]
  },
  {
    "id": 4,
    "nameInArabic": "الإسكندرية",
    "nameInEnglish": "Alexandria",
    "citiesAndVillages": [
      {"id": 89, "nameInArabic": "أبو قير، الإسكندرية", "nameInEnglish": "Abu Qir"},
      {"id": 90, "nameInArabic": "الأزاريطة، الإسكندرية", "nameInEnglish": "El Azarita"},
      {"id": 91, "nameInArabic": "الإبراهيمية، الإسكندرية", "nameInEnglish": "Al Ibrahimiyyah"},
      {"id": 92, "nameInArabic": "الجمرك، الإسكندرية", "nameInEnglish": "El Gomrok"},
      {"id": 93, "nameInArabic": "الحضرة، الإسكندرية", "nameInEnglish": "Al Hadrah"},
      {"id": 94, "nameInArabic": "الدخيلة، الإسكندرية", "nameInEnglish": "Ad Dakhilah"},
      {"id": 95, "nameInArabic": "السيوف، الإسكندرية", "nameInEnglish": "El Soyof"},
      {"id": 96, "nameInArabic": "الصالحية، الإسكندرية", "nameInEnglish": "Salehia"},
      {"id": 97, "nameInArabic": "الظاهرية، الإسكندرية", "nameInEnglish": "Al Zaherya"},
      {"id": 98, "nameInArabic": "العامرية، الإسكندرية", "nameInEnglish": "Amreya"},
      {"id": 99, "nameInArabic": "العصافرة، الإسكندرية", "nameInEnglish": "Asafra"},
      {"id": 100, "nameInArabic": "العطارين، الإسكندرية", "nameInEnglish": "Al Attarin"},
      {"id": 101, "nameInArabic": "العوايد، الإسكندرية", "nameInEnglish": "awayed"},
      {"id": 102, "nameInArabic": "القباري، الإسكندرية", "nameInEnglish": "Kabbary"},
      {"id": 103, "nameInArabic": "اللبان، الإسكندرية", "nameInEnglish": "Labban"},
      {"id": 104, "nameInArabic": "المعمورة، الإسكندرية", "nameInEnglish": "Al Mamurah"},
      {"id": 105, "nameInArabic": "المكس، الإسكندرية", "nameInEnglish": "Al Max"},
      {"id": 106, "nameInArabic": "المنتزه، الإسكندرية", "nameInEnglish": "Montaza"},
      {"id": 107, "nameInArabic": "المندرة، الإسكندرية", "nameInEnglish": "El-Mandara"},
      {"id": 108, "nameInArabic": "المنشية، الإسكندرية", "nameInEnglish": "Mansheya"},
      {"id": 109, "nameInArabic": "النخيل، الإسكندرية", "nameInEnglish": "El-Nakheel"},
      {"id": 110, "nameInArabic": "النزهة، الإسكندرية", "nameInEnglish": "Nozha"},
      {"id": 111, "nameInArabic": "الورديان، الإسكندرية", "nameInEnglish": "Wardian"},
      {"id": 112, "nameInArabic": "باكوس، الإسكندرية", "nameInEnglish": "Bacos"},
      {"id": 113, "nameInArabic": "بحرى والأنفوشى، الإسكندرية", "nameInEnglish": "Al-Anfoushy"},
      {"id": 114, "nameInArabic": "برج العرب، الإسكندرية", "nameInEnglish": "Borg Al Arab"},
      {"id": 115, "nameInArabic": "بولكلي، الإسكندرية", "nameInEnglish": "Bolkly"},
      {"id": 116, "nameInArabic": "جليم، الإسكندرية", "nameInEnglish": "Glim"},
      {"id": 117, "nameInArabic": "جناكليس، الإسكندرية", "nameInEnglish": "Gianaclis"},
      {"id": 118, "nameInArabic": "رأس التين، الإسكندرية", "nameInEnglish": "Ras el-Tin"},
      {"id": 119, "nameInArabic": "رشدي، الإسكندرية", "nameInEnglish": "Roshdy"},
      {"id": 120, "nameInArabic": "زيزينيا، الإسكندرية", "nameInEnglish": "Zezenia"},
      {"id": 121, "nameInArabic": "سابا باشا، الإسكندرية", "nameInEnglish": "Saba Pasha"},
      {"id": 122, "nameInArabic": "سان ستيفانو، الإسكندرية", "nameInEnglish": "San Stefano"},
      {"id": 123, "nameInArabic": "سبورتنج، الإسكندرية", "nameInEnglish": "Sporting"},
      {"id": 124, "nameInArabic": "ستانلي، الإسكندرية", "nameInEnglish": "Stanley"},
      {"id": 125, "nameInArabic": "سموحة، الإسكندرية", "nameInEnglish": "Smouha"},
      {"id": 126, "nameInArabic": "سيدي بشر، الإسكندرية", "nameInEnglish": "Sidi Bishr"},
      {"id": 127, "nameInArabic": "سيدي جابر، الإسكندرية", "nameInEnglish": "Sidi Gabir"},
      {"id": 128, "nameInArabic": "شاطبي، الإسكندرية", "nameInEnglish": "Shatby"},
      {"id": 129, "nameInArabic": "شدس، الإسكندرية", "nameInEnglish": "Shods"},
      {"id": 130, "nameInArabic": "طوسون، الإسكندرية", "nameInEnglish": "Tosson"},
      {"id": 131, "nameInArabic": "عجمي، الإسكندرية", "nameInEnglish": "El-Agamy"},
      {"id": 132, "nameInArabic": "فلمنج، الإسكندرية", "nameInEnglish": "Flemig"},
      {"id": 133, "nameInArabic": "فيكتوريا، الإسكندرية", "nameInEnglish": "Victoria"},
      {"id": 134, "nameInArabic": "كامب شيزار، الإسكندرية", "nameInEnglish": "Camp Shezar"},
      {"id": 135, "nameInArabic": "كرموز، الإسكندرية", "nameInEnglish": "Karmoz"},
      {"id": 136, "nameInArabic": "كفر عبدو، الإسكندرية", "nameInEnglish": "afr Abdu"},
      {"id": 137, "nameInArabic": "كليوباترا، الإسكندرية", "nameInEnglish": "Cleopatra"},
      {"id": 138, "nameInArabic": "كوم الدكة، الإسكندرية", "nameInEnglish": "Kom El Deka"},
      {"id": 139, "nameInArabic": "لوران، الإسكندرية", "nameInEnglish": "Louran"},
      {"id": 140, "nameInArabic": "محرّم بيك، الإسكندرية", "nameInEnglish": "Moharam Bek"},
      {"id": 141, "nameInArabic": "محطة الرمل، الإسكندرية", "nameInEnglish": "Mahatet El Raml"},
      {"id": 142, "nameInArabic": "ميامي، الإسكندرية", "nameInEnglish": "Miami"},
      {"id": 143, "nameInArabic": "مينا البصل، الإسكندرية", "nameInEnglish": "Mina Al Basal"}
    ]
  },
  {
    "id": 5,
    "nameInArabic": "الإسماعيلية",
    "nameInEnglish": "Ismailia",
    "citiesAndVillages": [
      {"id": 144, "nameInArabic": "أبوصوير، الإسماعيلية", "nameInEnglish": "Abu Swear"},
      {"id": 145, "nameInArabic": "التل الكبير، الإسماعيلية", "nameInEnglish": "Tell El Kebir"},
      {"id": 146, "nameInArabic": "القصاصين، الإسماعيلية", "nameInEnglish": "Qassaseen"},
      {"id": 147, "nameInArabic": "القنطرة شرق، الإسماعيلية", "nameInEnglish": "Kantara East"},
      {"id": 148, "nameInArabic": "القنطرة غرب، الإسماعيلية", "nameInEnglish": "Kantara West"},
      {"id": 149, "nameInArabic": "فايد، الإسماعيلية", "nameInEnglish": "Fayed"}
    ]
  },
  {
    "id": 6,
    "nameInArabic": "البحر الأحمر",
    "nameInEnglish": "Red Sea",
    "citiesAndVillages": [
      {"id": 150, "nameInArabic": "الغردقة - أخرى، البحر الأحمر", "nameInEnglish": "Hurghada"},
      {"id": 151, "nameInArabic": "الغردقة - الجونة، البحر الأحمر", "nameInEnglish": "El Gouna"},
      {"id": 152, "nameInArabic": "القصير، البحر الأحمر", "nameInEnglish": "Quseer"},
      {"id": 153, "nameInArabic": "رأس غارب، البحر الأحمر", "nameInEnglish": "Ras Ghareb"},
      {"id": 154, "nameInArabic": "سفاجا، البحر الأحمر", "nameInEnglish": "Safaga"},
      {"id": 155, "nameInArabic": "سهل حشيش، البحر الأحمر", "nameInEnglish": "Sahl Hasheesh"},
      {"id": 156, "nameInArabic": "شلاتين، البحر الأحمر", "nameInEnglish": "Shalateen"},
      {"id": 157, "nameInArabic": "مرسى علم، البحر الأحمر", "nameInEnglish": "Marsa Alam"}
    ]
  },
  {
    "id": 7,
    "nameInArabic": "البحيرة",
    "nameInEnglish": "El Beheira",
    "citiesAndVillages": [
      {"id": 158, "nameInArabic": "أبو المطامير، البحيرة", "nameInEnglish": "Abu Al Matamir"},
      {"id": 159, "nameInArabic": "أبو حمص، البحيرة", "nameInEnglish": "Abu Hummus"},
      {"id": 160, "nameInArabic": "إدكو، البحيرة", "nameInEnglish": "Idku"},
      {"id": 161, "nameInArabic": "الدلنجات، البحيرة", "nameInEnglish": "Ad Dilinjat"},
      {"id": 162, "nameInArabic": "الرحمانية، البحيرة", "nameInEnglish": "AR Rahmaneyah"},
      {"id": 163, "nameInArabic": "المحمودية، البحيرة", "nameInEnglish": "El-Mahmoudeya"},
      {"id": 164, "nameInArabic": "النوبارية الجديدة، البحيرة", "nameInEnglish": "Nubaria Canal"},
      {"id": 165, "nameInArabic": "ايتاي البارود، البحيرة", "nameInEnglish": "Itay Al Barud"},
      {"id": 166, "nameInArabic": "بدر، البحيرة", "nameInEnglish": "Badr"},
      {"id": 167, "nameInArabic": "حوش عيسى، البحيرة", "nameInEnglish": "Housh Eissa"},
      {"id": 168, "nameInArabic": "دمنهور، البحيرة", "nameInEnglish": "Damanhour"},
      {"id": 169, "nameInArabic": "رشيد، البحيرة", "nameInEnglish": "Rasheed"},
      {"id": 170, "nameInArabic": "شبراخيت، البحيرة", "nameInEnglish": "Shubrakhit"},
      {"id": 171, "nameInArabic": "كفر الدوار، البحيرة", "nameInEnglish": "Kafr El-Dawar"},
      {"id": 172, "nameInArabic": "كوم حمادة، البحيرة", "nameInEnglish": "Kawm Hamadah"},
      {"id": 173, "nameInArabic": "وادي النطرون، البحيرة", "nameInEnglish": "Natrn Valley"}
    ]
  },
  {
    "id": 8,
    "nameInArabic": "مرسي مطروح",
    "nameInEnglish": "Marsa Matruh",
    "citiesAndVillages": [
      {"id": 174, "nameInArabic": "الحمام، مطروح", "nameInEnglish": "El-Hamam"},
      {"id": 175, "nameInArabic": "الساحل الشمالي، مطروح", "nameInEnglish": "North-Coast"},
      {"id": 176, "nameInArabic": "السلوم، مطروح", "nameInEnglish": "El Salloum"},
      {"id": 177, "nameInArabic": "الضبعة، مطروح", "nameInEnglish": "El Dabaa"},
      {"id": 178, "nameInArabic": "العلمين، مطروح", "nameInEnglish": "El-Alamein"},
      {"id": 179, "nameInArabic": "النجيلة، مطروح", "nameInEnglish": "El Negaila"},
      {"id": 180, "nameInArabic": "براني، مطروح", "nameInEnglish": "Sidi Barrani"},
      {"id": 181, "nameInArabic": "سيوة، مطروح", "nameInEnglish": "Siwa Oasis"},
      {"id": 182, "nameInArabic": "مارينا العلمين، مطروح", "nameInEnglish": "Marina El-Alamein"}
    ]
  },
  {
    "id": 9,
    "nameInArabic": "الجيزة",
    "nameInEnglish": "Giza",
    "citiesAndVillages": [
      {"id": 183, "nameInArabic": "6 أكتوبر، الجيزة", "nameInEnglish": "6th of October"},
      {"id": 184, "nameInArabic": "أبو رواش، الجيزة", "nameInEnglish": "Abu Rawash"},
      {"id": 185, "nameInArabic": "أرض اللواء، الجيزة", "nameInEnglish": "Ard El-Lewa"},
      {"id": 186, "nameInArabic": "أوسيم، الجيزة", "nameInEnglish": "Ausim"},
      {"id": 187, "nameInArabic": "إمبابة، الجيزة", "nameInEnglish": "Imbabah"},
      {"id": 188, "nameInArabic": "البدرشين، الجيزة", "nameInEnglish": "Badrshein"},
      {"id": 189, "nameInArabic": "البراجيل، الجيزة", "nameInEnglish": "El-Baragil"},
      {"id": 190, "nameInArabic": "الحرانية، الجيزة", "nameInEnglish": "El Haraneya"},
      {"id": 191, "nameInArabic": "الحوامدية، الجيزة", "nameInEnglish": "El-Hawamdeya"},
      {"id": 192, "nameInArabic": "الدقى، الجيزة", "nameInEnglish": "Ad Doqi"},
      {"id": 193, "nameInArabic": "الرماية، الجيزة", "nameInEnglish": "Al Remaya"},
      {"id": 194, "nameInArabic": "الشيخ زايد، الجيزة", "nameInEnglish": "Sheikh Zayed"},
      {"id": 195, "nameInArabic": "الصحفيين، الجيزة", "nameInEnglish": "sahafieen"},
      {"id": 196, "nameInArabic": "الصف، الجيزة", "nameInEnglish": "El-Saf"},
      {"id": 197, "nameInArabic": "العجوزة، الجيزة", "nameInEnglish": "Al Agouzah"},
      {"id": 198, "nameInArabic": "العزيزية، الجيزة", "nameInEnglish": "Al Azizeyah"},
      {"id": 199, "nameInArabic": "العمرانية، الجيزة", "nameInEnglish": "Omrania"},
      {"id": 200, "nameInArabic": "العياط، الجيزة", "nameInEnglish": "Al-Ayat"},
      {"id": 201, "nameInArabic": "القرية الفرعونية، الجيزة", "nameInEnglish": "pharaonic-village"},
      {"id": 202, "nameInArabic": "الكيت كات، الجيزة", "nameInEnglish": "Kit Kat"},
      {"id": 203, "nameInArabic": "المنصورية، الجيزة", "nameInEnglish": "Al Mansouria"},
      {"id": 204, "nameInArabic": "المنيب، الجيزة", "nameInEnglish": "El-Monib"},
      {"id": 205, "nameInArabic": "المهندسين، الجيزة", "nameInEnglish": "Mohandessin"},
      {"id": 206, "nameInArabic": "الهرم، الجيزة", "nameInEnglish": "El-Haram"},
      {"id": 207, "nameInArabic": "الوراق، الجيزة", "nameInEnglish": "El Warraq"},
      {"id": 208, "nameInArabic": "بشتيل، الجيزة", "nameInEnglish": "Bashtil"},
      {"id": 209, "nameInArabic": "بني سلامة، الجيزة", "nameInEnglish": "Bani Salamah"},
      {"id": 210, "nameInArabic": "بولاق الدكرور، الجيزة", "nameInEnglish": "Boulaq Ad Dakrour"},
      {"id": 211, "nameInArabic": "ترسا، الجيزة", "nameInEnglish": "Tersa"},
      {"id": 212, "nameInArabic": "جزيرة الدهب، الجيزة", "nameInEnglish": "Dahab Island"},
      {"id": 213, "nameInArabic": "حدائق الاهرام، الجيزة", "nameInEnglish": "Pyramids Gardens"},
      {"id": 214, "nameInArabic": "دهشور، الجيزة", "nameInEnglish": "Dahshur"},
      {"id": 215, "nameInArabic": "ساقية مكى، الجيزة", "nameInEnglish": "Saqiyet Mekki"},
      {"id": 216, "nameInArabic": "سقارة، الجيزة", "nameInEnglish": "Saqqara"},
      {"id": 217, "nameInArabic": "صفط، الجيزة", "nameInEnglish": "Saft Al Laban"},
      {"id": 218, "nameInArabic": "غرب سوميد، الجيزة", "nameInEnglish": "West Somid"},
      {"id": 219, "nameInArabic": "فيصل، الجيزة", "nameInEnglish": "Faisal"},
      {"id": 220, "nameInArabic": "كرداسة، الجيزة", "nameInEnglish": "Kirdasah"},
      {"id": 221, "nameInArabic": "كفر طهرمس، الجيزة", "nameInEnglish": "Kafr Tohormos"},
      {"id": 222, "nameInArabic": "مريوطية، الجيزة", "nameInEnglish": "Al Maryotaya"},
      {"id": 223, "nameInArabic": "ميت عقبة، الجيزة", "nameInEnglish": "Mit Akaba"},
      {"id": 224, "nameInArabic": "ناهيا، الجيزة", "nameInEnglish": "Nahia"},
      {"id": 225, "nameInArabic": "وردان، الجيزة", "nameInEnglish": "Wardan"}
    ]
  },
  {
    "id": 10,
    "nameInArabic": "الدقهلية",
    "nameInEnglish": "Dakahlia",
    "citiesAndVillages": [
      {"id": 226, "nameInArabic": "أجا، الدقهلية", "nameInEnglish": "Aga"},
      {"id": 227, "nameInArabic": "أخطاب، الدقهلية", "nameInEnglish": "Ikhtab"},
      {"id": 228, "nameInArabic": "الجمالية، الدقهلية", "nameInEnglish": "Al Jamaliyah"},
      {"id": 229, "nameInArabic": "السنبلاوين، الدقهلية", "nameInEnglish": "El-Senbellawein"},
      {"id": 230, "nameInArabic": "المطرية، الدقهلية", "nameInEnglish": "El Matareya"},
      {"id": 231, "nameInArabic": "المنزلة، الدقهلية", "nameInEnglish": "Al Manzalah"},
      {"id": 232, "nameInArabic": "المنصورة، الدقهلية", "nameInEnglish": "Mansoura"},
      {"id": 233, "nameInArabic": "بلقاس، الدقهلية", "nameInEnglish": "Belkas"},
      {"id": 234, "nameInArabic": "بني عبيد، الدقهلية", "nameInEnglish": "Beni Ebeid"},
      {"id": 235, "nameInArabic": "تمى الامديد، الدقهلية", "nameInEnglish": "Temay El Amdeed"},
      {"id": 236, "nameInArabic": "جمصه، الدقهلية", "nameInEnglish": "Gamasa"},
      {"id": 237, "nameInArabic": "دكرنس، الدقهلية", "nameInEnglish": "dikirnis"},
      {"id": 238, "nameInArabic": "شربين، الدقهلية", "nameInEnglish": "Dikirnis"},
      {"id": 239, "nameInArabic": "طلخا، الدقهلية", "nameInEnglish": "talkha"},
      {"id": 240, "nameInArabic": "منية النصر، الدقهلية", "nameInEnglish": "Menyet El Nasr"},
      {"id": 241, "nameInArabic": "ميت سلسيل، الدقهلية", "nameInEnglish": "Mit Salsil"},
      {"id": 242, "nameInArabic": "ميت غمر، الدقهلية", "nameInEnglish": "Mit Ghamr"},
      {"id": 243, "nameInArabic": "نبروه، الدقهلية", "nameInEnglish": "Nabaruh"}
    ]
  },
  {
    "id": 11,
    "nameInArabic": "السويس",
    "nameInEnglish": "Suez",
    "citiesAndVillages": [
      {"id": 244, "nameInArabic": "العين السخنة، السويس", "nameInEnglish": "Ain Sokhna"},
      {"id": 245, "nameInArabic": "حى الجناين، السويس", "nameInEnglish": "Al Ganayen"},
      {"id": 246, "nameInArabic": "حي الأربعين، السويس", "nameInEnglish": "Arbaeen"},
      {"id": 247, "nameInArabic": "حي عتاقة، السويس", "nameInEnglish": "Attaka"},
      {"id": 248, "nameInArabic": "فيصل، السويس", "nameInEnglish": "Faisal Suez"}
    ]
  },
  {
    "id": 12,
    "nameInArabic": "الشرقية",
    "nameInEnglish": "Ash Sharqia",
    "citiesAndVillages": [
      {"id": 249, "nameInArabic": "أبو حماد، الشرقية", "nameInEnglish": "Abou Hammad"},
      {"id": 250, "nameInArabic": "أبو كبير، الشرقية", "nameInEnglish": "Abu Kibir"},
      {"id": 251, "nameInArabic": "أولاد صقر، الشرقية", "nameInEnglish": "Awlad Saqr"},
      {"id": 252, "nameInArabic": "الإبراهيمية، الشرقية", "nameInEnglish": "El Ibrahimiya"},
      {"id": 253, "nameInArabic": "الحسينية، الشرقية", "nameInEnglish": "El Husseiniya"},
      {"id": 254, "nameInArabic": "الزقازيق، الشرقية", "nameInEnglish": "Zagazig"},
      {"id": 255, "nameInArabic": "الصالحية الجديدة، الشرقية", "nameInEnglish": "New Salhia"},
      {"id": 256, "nameInArabic": "العاشر من رمضان، الشرقية", "nameInEnglish": "10th of Ramadan"},
      {"id": 257, "nameInArabic": "القرين، الشرقية", "nameInEnglish": "Al Qorin"},
      {"id": 258, "nameInArabic": "القنايات، الشرقية", "nameInEnglish": "Alqnayat"},
      {"id": 259, "nameInArabic": "بلبيس، الشرقية", "nameInEnglish": "Belbes"},
      {"id": 260, "nameInArabic": "ديرب نجم، الشرقية", "nameInEnglish": "Dyarb Negm"},
      {"id": 261, "nameInArabic": "فاقوس، الشرقية", "nameInEnglish": "Faqus"},
      {"id": 262, "nameInArabic": "كفر صقر، الشرقية", "nameInEnglish": "Kafr Saqr"},
      {"id": 263, "nameInArabic": "مشتول السوق، الشرقية", "nameInEnglish": "Mashtul as Suq"},
      {"id": 264, "nameInArabic": "منيا القمح، الشرقية", "nameInEnglish": "Minya Al Qamh"},
      {"id": 265, "nameInArabic": "ههيا، الشرقية", "nameInEnglish": "Hihya"}
    ]
  },
  {
    "id": 13,
    "nameInArabic": "الغربية",
    "nameInEnglish": "Gharbia",
    "citiesAndVillages": [
      {"id": 266, "nameInArabic": "السنطة، الغربية", "nameInEnglish": "El Santa"},
      {"id": 267, "nameInArabic": "المحلة الكبرى، الغربية", "nameInEnglish": "El-Mahalla El-Kubra"},
      {"id": 268, "nameInArabic": "بسيون، الغربية", "nameInEnglish": "Basioun"},
      {"id": 269, "nameInArabic": "زفتى، الغربية", "nameInEnglish": "Zifta"},
      {"id": 270, "nameInArabic": "سمنود، الغربية", "nameInEnglish": "Samanoud"},
      {"id": 271, "nameInArabic": "طنطا، الغربية", "nameInEnglish": "Tanta"},
      {"id": 272, "nameInArabic": "قطور، الغربية", "nameInEnglish": "Qutur"},
      {"id": 273, "nameInArabic": "كفر الزيات، الغربية", "nameInEnglish": "kafr-al-zayat"}
    ]
  },
  {
    "id": 14,
    "nameInArabic": "الفيوم",
    "nameInEnglish": "Faiyum",
    "citiesAndVillages": [
      {"id": 274, "nameInArabic": "أطسا، الفيوم", "nameInEnglish": "ITSA"},
      {"id": 275, "nameInArabic": "إبشواي، الفيوم", "nameInEnglish": "Ibshway"},
      {"id": 276, "nameInArabic": "الفيوم الجديدة، الفيوم", "nameInEnglish": "New fayoum"},
      {"id": 277, "nameInArabic": "سنورس، الفيوم", "nameInEnglish": "Sinnuras"},
      {"id": 278, "nameInArabic": "طامية، الفيوم", "nameInEnglish": "Tamiyyah"},
      {"id": 279, "nameInArabic": "يوسف الصديق، الفيوم", "nameInEnglish": "Yousef El Seddik"}
    ]
  },
  {
    "id": 15,
    "nameInArabic": "القليوبية",
    "nameInEnglish": "Al Qalyubia",
    "citiesAndVillages": [
      {"id": 280, "nameInArabic": "الخانكة، القليوبية", "nameInEnglish": "Al Khankah"},
      {"id": 281, "nameInArabic": "الخصوص، القليوبية", "nameInEnglish": "Al Khosous"},
      {"id": 282, "nameInArabic": "العبور، القليوبية", "nameInEnglish": "El Obour"},
      {"id": 283, "nameInArabic": "القناطر الخيرية، القليوبية", "nameInEnglish": "El Qanater El Khayreya"},
      {"id": 284, "nameInArabic": "بنها، القليوبية", "nameInEnglish": "Banha"},
      {"id": 285, "nameInArabic": "بهتيم، القليوبية", "nameInEnglish": "Bahtim"},
      {"id": 286, "nameInArabic": "زاويه النجار، القليوبية", "nameInEnglish": "Zawya El-Naggar"},
      {"id": 287, "nameInArabic": "شبرا الخيمة، القليوبية", "nameInEnglish": "Shubra Al Khaymah"},
      {"id": 288, "nameInArabic": "شبين القناطر، القليوبية", "nameInEnglish": "Shibin el-Qanater"},
      {"id": 289, "nameInArabic": "طوخ، القليوبية", "nameInEnglish": "Toukh"},
      {"id": 290, "nameInArabic": "قليوب، القليوبية", "nameInEnglish": "Qalyub"},
      {"id": 291, "nameInArabic": "قها، القليوبية", "nameInEnglish": "Qaha"},
      {"id": 292, "nameInArabic": "كفر شكر، القليوبية", "nameInEnglish": "Kafr Shukr"}
    ]
  },
  {
    "id": 16,
    "nameInArabic": "المنوفية",
    "nameInEnglish": "Menofia",
    "citiesAndVillages": [
      {"id": 293, "nameInArabic": "أشمون، المنوفية", "nameInEnglish": "Ashmoun"},
      {"id": 294, "nameInArabic": "الباجور، المنوفية", "nameInEnglish": "El-Bagour"},
      {"id": 295, "nameInArabic": "السادات، المنوفية", "nameInEnglish": "El Sadat"},
      {"id": 296, "nameInArabic": "الشهداء، المنوفية", "nameInEnglish": "Shuhada"},
      {"id": 297, "nameInArabic": "بركة السبع، المنوفية", "nameInEnglish": "Berket El-Sabaa"},
      {"id": 298, "nameInArabic": "تلا، المنوفية", "nameInEnglish": "Tala"},
      {"id": 299, "nameInArabic": "سرس الليان، المنوفية", "nameInEnglish": "Sers Al-Lyan"},
      {"id": 300, "nameInArabic": "شبين الكوم، المنوفية", "nameInEnglish": "Shebeen El-Kom"},
      {"id": 301, "nameInArabic": "قويسنا، المنوفية", "nameInEnglish": "Quwaysna"},
      {"id": 302, "nameInArabic": "منوف، المنوفية", "nameInEnglish": "Minuf"},
      {"id": 303, "nameInArabic": "ميت العز، المنوفية", "nameInEnglish": "Mit El-Ezz"}
    ]
  },
  {
    "id": 17,
    "nameInArabic": "المنيا",
    "nameInEnglish": "Minya",
    "citiesAndVillages": [
      {"id": 304, "nameInArabic": "أبو قرقاص، المنيا", "nameInEnglish": "Abu Qurqas"},
      {"id": 305, "nameInArabic": "العدوة، المنيا", "nameInEnglish": "El Idwa"},
      {"id": 306, "nameInArabic": "المنيا الجديدة، المنيا", "nameInEnglish": "New Minya"},
      {"id": 307, "nameInArabic": "بني مزار، المنيا", "nameInEnglish": "Bani Mazar"},
      {"id": 308, "nameInArabic": "دير مواس، المنيا", "nameInEnglish": "Dayr Mawas"},
      {"id": 309, "nameInArabic": "سمالوط، المنيا", "nameInEnglish": "Samalut"},
      {"id": 310, "nameInArabic": "مطاي، المنيا", "nameInEnglish": "Matay"},
      {"id": 311, "nameInArabic": "مغاغة، المنيا", "nameInEnglish": "Maghagha"},
      {"id": 312, "nameInArabic": "ملوي، المنيا", "nameInEnglish": "Mallawi"}
    ]
  },
  {
    "id": 18,
    "nameInArabic": "الوادي الجديد",
    "nameInEnglish": "New Valley",
    "citiesAndVillages": [
      {"id": 313, "nameInArabic": "الخارجة، الوادي الجديد", "nameInEnglish": "Kharga"},
      {"id": 314, "nameInArabic": "الداخلة، الوادي الجديد", "nameInEnglish": "Dakhla"},
      {"id": 315, "nameInArabic": "الفرافرة، الوادي الجديد", "nameInEnglish": "Farafra"},
      {"id": 316, "nameInArabic": "بلاط، الوادي الجديد", "nameInEnglish": "Balat"},
      {"id": 317, "nameInArabic": "مدينة موط، الوادي الجديد", "nameInEnglish": "Mut"}
    ]
  },
  {
    "id": 19,
    "nameInArabic": "بني سويف",
    "nameInEnglish": "Beni Suef",
    "citiesAndVillages": [
      {"id": 318, "nameInArabic": "إهناسيا، بني سويف", "nameInEnglish": "Ihnasiyah"},
      {"id": 319, "nameInArabic": "الفشن، بني سويف", "nameInEnglish": "Al Fashn"},
      {"id": 320, "nameInArabic": "الواسطى، بني سويف", "nameInEnglish": "El Wasta"},
      {"id": 321, "nameInArabic": "ببا، بني سويف", "nameInEnglish": "Biba"},
      {"id": 322, "nameInArabic": "بني سويف الجديدة، بني سويف", "nameInEnglish": "New Beni Suef"},
      {"id": 323, "nameInArabic": "سمسطا، بني سويف", "nameInEnglish": "Sumusta"},
      {"id": 324, "nameInArabic": "ناصر، بني سويف", "nameInEnglish": "Naser"}
    ]
  },
  {
    "id": 20,
    "nameInArabic": "بورسعيد",
    "nameInEnglish": "port-Said",
    "citiesAndVillages": [
      {"id": 325, "nameInArabic": "حي الجنوب، بورسعيد", "nameInEnglish": "Gharb District"},
      {"id": 326, "nameInArabic": "حي الزهور، بورسعيد", "nameInEnglish": "Al-Zohour District"},
      {"id": 327, "nameInArabic": "حي الشرق، بورسعيد", "nameInEnglish": "Al-Sharq District"},
      {"id": 328, "nameInArabic": "حي الضواحي، بورسعيد", "nameInEnglish": "Al-Dawahy District"},
      {"id": 329, "nameInArabic": "حي العرب، بورسعيد", "nameInEnglish": "Al-Arab District"},
      {"id": 330, "nameInArabic": "حي المناخ، بورسعيد", "nameInEnglish": "Al-Manakh District"},
      {"id": 331, "nameInArabic": "مدينة بورفؤاد، بورسعيد", "nameInEnglish": "Port Fuad"}
    ]
  },
  {
    "id": 21,
    "nameInArabic": "جنوب سيناء",
    "nameInEnglish": "South Sinai",
    "citiesAndVillages": [
      {"id": 332, "nameInArabic": "أبو رديس، جنوب سيناء", "nameInEnglish": "Abu Rudeis"},
      {"id": 333, "nameInArabic": "أبو زنيمة، جنوب سيناء", "nameInEnglish": "Abu Zenima"},
      {"id": 334, "nameInArabic": "دهب، جنوب سيناء", "nameInEnglish": "Dahab"},
      {"id": 335, "nameInArabic": "رأس سدر، جنوب سيناء", "nameInEnglish": "Ras Sedr"},
      {"id": 336, "nameInArabic": "سانت كاترين، جنوب سيناء", "nameInEnglish": "Saint Catherine"},
      {"id": 337, "nameInArabic": "شرم الشيخ، جنوب سيناء", "nameInEnglish": "Sharm El-Sheikh"},
      {"id": 338, "nameInArabic": "طابا، جنوب سيناء", "nameInEnglish": "Taba"},
      {"id": 339, "nameInArabic": "طور سيناء، جنوب سيناء", "nameInEnglish": "El Tor"},
      {"id": 340, "nameInArabic": "نويبع، جنوب سيناء", "nameInEnglish": "Nuweibaa"}
    ]
  },
  {
    "id": 22,
    "nameInArabic": "دمياط",
    "nameInEnglish": "Damietta",
    "citiesAndVillages": [
      {"id": 341, "nameInArabic": "الروضة، دمياط", "nameInEnglish": "El-Rawda"},
      {"id": 342, "nameInArabic": "الزرقا، دمياط", "nameInEnglish": "AZ Zarqa"},
      {"id": 343, "nameInArabic": "السرو، دمياط", "nameInEnglish": "Assarw"},
      {"id": 344, "nameInArabic": "رأس البر، دمياط", "nameInEnglish": "Ras El-Bar"},
      {"id": 345, "nameInArabic": "عزبة البرج، دمياط", "nameInEnglish": "Izbat Al Burj"},
      {"id": 346, "nameInArabic": "فارسكور، دمياط", "nameInEnglish": "Fareskour"},
      {"id": 347, "nameInArabic": "كفر البطيخ، دمياط", "nameInEnglish": "Kafr Al Battikh"},
      {"id": 348, "nameInArabic": "كفر سعد، دمياط", "nameInEnglish": "Kafr Saad"},
      {"id": 349, "nameInArabic": "ميت أبوغالب، دمياط", "nameInEnglish": "Mit Abu Ghaleb"}
    ]
  },
  {
    "id": 23,
    "nameInArabic": "سوهاج",
    "nameInEnglish": "Sohag",
    "citiesAndVillages": [
      {"id": 350, "nameInArabic": "أخميم، سوهاج", "nameInEnglish": "Akhmim"},
      {"id": 351, "nameInArabic": "البلينا، سوهاج", "nameInEnglish": "Al Balyana"},
      {"id": 352, "nameInArabic": "العسيرات، سوهاج", "nameInEnglish": "El-Usayrat"},
      {"id": 353, "nameInArabic": "المراغة، سوهاج", "nameInEnglish": "El Maragha"},
      {"id": 354, "nameInArabic": "المنشاة، سوهاج", "nameInEnglish": "Al Minshah"},
      {"id": 355, "nameInArabic": "جرجا، سوهاج", "nameInEnglish": "Girga"},
      {"id": 356, "nameInArabic": "جهينة، سوهاج", "nameInEnglish": "Juhaynah"},
      {"id": 357, "nameInArabic": "دارالسلام، سوهاج", "nameInEnglish": "Dar El-Salam"},
      {"id": 358, "nameInArabic": "ساقلتة، سوهاج", "nameInEnglish": "Saqultah"},
      {"id": 359, "nameInArabic": "طما، سوهاج", "nameInEnglish": "Tama"},
      {"id": 360, "nameInArabic": "طهطا، سوهاج", "nameInEnglish": "Tahta"}
    ]
  },
  {
    "id": 24,
    "nameInArabic": "شمال سيناء",
    "nameInEnglish": "North Sinai",
    "citiesAndVillages": [
      {"id": 361, "nameInArabic": "الحسنة، شمال سيناء", "nameInEnglish": "Hasna"},
      {"id": 362, "nameInArabic": "الشيخ زويد، شمال سيناء", "nameInEnglish": "Sheikh Zuweid"},
      {"id": 363, "nameInArabic": "العريش، شمال سيناء", "nameInEnglish": "Arish"},
      {"id": 364, "nameInArabic": "بئر العبد، شمال سيناء", "nameInEnglish": "Bir al-Abd"},
      {"id": 365, "nameInArabic": "رفح، شمال سيناء", "nameInEnglish": "Rafah"},
      {"id": 366, "nameInArabic": "نخل، شمال سيناء", "nameInEnglish": "Nekhel"}
    ]
  },
  {
    "id": 25,
    "nameInArabic": "قنا",
    "nameInEnglish": "Qena",
    "citiesAndVillages": [
      {"id": 367, "nameInArabic": "أبو تشت، قنا", "nameInEnglish": "Abu Tisht"},
      {"id": 368, "nameInArabic": "الوقف، قنا", "nameInEnglish": "Al Waqf"},
      {"id": 369, "nameInArabic": "دشنا. قنا", "nameInEnglish": "Dishna"},
      {"id": 370, "nameInArabic": "فرشوط، قنا", "nameInEnglish": "Farshut"},
      {"id": 371, "nameInArabic": "قفط، قنا", "nameInEnglish": "Qift"},
      {"id": 372, "nameInArabic": "قوص، قنا", "nameInEnglish": "Qus"},
      {"id": 373, "nameInArabic": "نجع حمادي، قنا", "nameInEnglish": "Nagaa Hammadi"},
      {"id": 374, "nameInArabic": "نقادة، قنا", "nameInEnglish": "Naqadah"}
    ]
  },
  {
    "id": 26,
    "nameInArabic": "كفر الشيخ",
    "nameInEnglish": "Kafr El-Shaikh",
    "citiesAndVillages": [
      {"id": 375, "nameInArabic": "البرلس، كفر الشيخ", "nameInEnglish": "Burullus"},
      {"id": 376, "nameInArabic": "الحامول، كفر الشيخ", "nameInEnglish": "El-Hamoul"},
      {"id": 377, "nameInArabic": "الرياض، كفر الشيخ", "nameInEnglish": "El-Reyad"},
      {"id": 378, "nameInArabic": "بلطيم، كفر الشيخ", "nameInEnglish": "Baltim"},
      {"id": 379, "nameInArabic": "بيلا، كفر الشيخ", "nameInEnglish": "Biyala"},
      {"id": 380, "nameInArabic": "دسوق، كفر الشيخ", "nameInEnglish": "Desouk"},
      {"id": 381, "nameInArabic": "سيدى سالم، كفر الشيخ", "nameInEnglish": "Sidi Salem"},
      {"id": 382, "nameInArabic": "فوه، كفر الشيخ", "nameInEnglish": "Fouh"},
      {"id": 383, "nameInArabic": "قلين، كفر الشيخ", "nameInEnglish": "Qillin"},
      {"id": 384, "nameInArabic": "مطوبس، كفر الشيخ", "nameInEnglish": "Motobas"}
    ]
  },
  {
    "id": 27,
    "nameInArabic": "الأقصر",
    "nameInEnglish": "Luxor",
    "citiesAndVillages": [
      {"id": 385, "nameInArabic": "أرمنت، الأقصر", "nameInEnglish": "Armant"},
      {"id": 386, "nameInArabic": "إسنا، الأقصر", "nameInEnglish": "Esna"},
      {"id": 387, "nameInArabic": "البياضية، الأقصر", "nameInEnglish": "Bayadeya"},
      {"id": 388, "nameInArabic": "الزينية، الأقصر", "nameInEnglish": "AZ Zayniyyah"},
      {"id": 389, "nameInArabic": "الطود، الأقصر", "nameInEnglish": "Al Toud City"},
      {"id": 390, "nameInArabic": "القرنه، الأقصر", "nameInEnglish": "Al Qarnah"}
    ]
  }
];